### ISSUE TITLE
Delayed flow deallocation after the client closes the socket desc.

### ISSUE THREAD

**Issue by kr1stj0n** [IRATI/stack#1279]
I am running an experiment depicted by the below topology:
IperfClient<----(TCP)---->**C-Proxy**<-------RINA-Router------->**S-Proxy**<----(TCP)---->Iperf Server

C-Proxy waits for an incoming TCP connection and then tries to allocate a RINA Flow between the S-Proxy, which establishes a TCP connection with the Iperf Server and then responds to the flow.

Everything works just fine, until the closing of the communication.
- After the IperfClient is done, it closes the TCP socket.
- C-Proxy read() 0 bytes from the socket and it understands that it was close by the client, so it closes the socket descriptor of the RINA flow, thus invoking a deallocation of the Flow.
- After getting the last bytes, S-Proxy is polling the socket descr. but the select() just timeouts for a while.

To sum up, there is a considerable delay (let's say ~5 sec) in the deallocation of the flow, requested remotely. This affects the time when the IperfServer closes the connection, so the calculation of the bandwidth is wrong.
I also tried with other RINA application like rinacat and rina-echo-time and it was the same. The server closes, but after a while.
I get these ERROR messages in the server side that occurs after the client closes the socket and invokes a deallocation.
_ubuntu kernel: [80500.162710] rina-kfa(ERR): There is no flow bound to port-id 62_
_#ipcm.flow-alloc (ERR)[flow_deallocation_requested_event_handler]: : Cannot find the IPC process that provides the flow with port-id 62_

More logs in the attached files.

Is this a ``normal'' behaviour of the stack or smth. else is going on?

[client-proxy_ipcm.log](https://github.com/IRATI/stack/files/2941145/client-proxy_ipcm.log)
[client-proxy_ipcp.log](https://github.com/IRATI/stack/files/2941146/client-proxy_ipcp.log)
[client-syslog.log](https://github.com/IRATI/stack/files/2941147/client-syslog.log)
[server-proxy_ipcm.log](https://github.com/IRATI/stack/files/2941148/server-proxy_ipcm.log)
[server-proxy_ipcp.log](https://github.com/IRATI/stack/files/2941149/server-proxy_ipcp.log)
[server-syslog.log](https://github.com/IRATI/stack/files/2941150/server-syslog.log)

**Comment by kr1stj0n** [comment]
Great, thanks!
I will test after the fix.

**Comment by edugrasa** [comment]
Fix available in my repo (https://github.com/edugrasa/stack.git), branch e2ens.

You'll have to rebuild and redeploy rinad and the kernel modules.

If it works I'll merge it into the main repo, otherwise let's kill the potential bugs I may have introduced first :)

**Comment by kr1stj0n** [comment]
I just tested and it works much better now :-)
The flow is deallocated almost immediately, but still the same Error logs are present.

Some logs that might be helpful:

_53218(1552327032)#librina.core (DBG): Added event of type(6) 6_FLOW_DEALLOCATED and sequence number 0 to events queue
53218(1552327032)#ipcm (DBG): Got event of type 6_FLOW_DEALLOCATED and sequence number 0
53218(1552327032)#ipcm.flow-alloc (INFO)[flow_deallocated_event_handler]: IPC process server.routing.DIF:1:: and local application stin::: informed that flow with port-id 10 has been deallocated remotely 

53218(1552327032)#librina.core (DBG): Added event of type(3) 3_FLOW_DEALLOCATION_REQUESTED and sequence number 3489318912 to events queue
53218(1552327032)#ipcm (DBG): Got event of type 3_FLOW_DEALLOCATION_REQUESTED and sequence number 3489318912
**53218(1552327032)#ipcm.flow-alloc (ERR)[flow_deallocation_requested_event_handler]: : Cannot find the IPC process that provides the flow with port-id 10**_

**From S-Proxy**:
_server rinaproxy[61180]: read 423 bytes from CLIENT (4)
server rinaproxy[61180]: write() 423 to server (S-Proxy reads and forwards the last chunk)
server rinaproxy[61180]: select() returned 0:
**server kernel: [ 5313.633521] rina-kfa(ERR): There is no flow bound to port-id 10
server kernel: [ 5313.633567] rina-kfa(ERR): There is no flow bound to port-id 10**
server rinaproxy[61180]: message repeated 82 times: [ select() returned 0: Success]
server rinaproxy[61180]: select() returned 1: (After a small delay, now close() from the other side causes select() to return.)
server rinaproxy[61180]: read 0 bytes from CLIENT (4) (Right now It understands that the socket was closed in the other sides)_

**Comment by edugrasa** [comment]
You can ignore the error logs (this is a pending thing, to improve logging and get rid of some misleading logs). If you have done a few more tests and everything seems ok, please let me know and I'll merge the changes :)

**Comment by kr1stj0n** [comment]
Yes, thanks - It does seem OK now :)
Closing the issue..
