### ISSUE TITLE
IPCM: set_event_result() is not thread safe

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#395]
<a href="https://github.com/vmaffione"><img src="https://avatars.githubusercontent.com/u/4920001?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vmaffione](https://github.com/vmaffione)**
_Friday Oct 03, 2014 at 08:26 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/392_

----

When wait_for_event() returns, the involved event handler has been executed (setting the result). However, there is no assurance that further events have not come right after the involved event, possibly overwriting the result to be read by the wait_for_event() caller.

**Comment by sandervrijders** [comment]
Fixed in current IPCM?

**Comment by vmaffione** [comment]
Not fixed. Marc is addressing these problems in the IPCM refactor.
