### ISSUE TITLE
Pristine-1.4:  Rerouting PDUs of a new/ongoing flow through different link fails

### ISSUE THREAD

**Issue by jvleur** [IRATI/stack#864]
**What is my Issue**
If I disconnect a redundant link between two nodes (by blocking the VLAN) New flow Allocation requests and ongoing flows do not reroute through other links other than the disconnected link. The fact that ongoing flows do not reroute is apparently a known issue but I could not find the github issue, I was told that new flows would reroute but this is not happening for me. When the disconnected link is brought back up before the neighbour_declared_dead event occurs, the network does restore to a state where new flows can be transfered.

**When does it occur**
I have set up a network as [Physical.pdf](https://github.com/IRATI/stack/files/124619/Physical.pdf) and [RINA.pdf](https://github.com/IRATI/stack/files/124620/RINA.pdf), note that these are 4 virtual nodes on one desktop. The configuration files of every virtual node are [here](https://github.com/IRATI/stack/files/124617/Config.zip).

For my issue to occur I disconnect the link between System 1 and System 2. After this I wait a while for the RIBs to update with new hops and start new rina-echo-time instances. System 1 is only possible to communicate with directly connected System 3. The RIB of System 1 shows the disappearance of System 2 (Address 17) but System 4 (Address 19) still remains. System 1 can't communicate with either System 4 or System 3.

**More details**
The address of the ipcp of System 4 also disappears from the RIB of System 1. When trying to send PDUs from System 3 rina-echo-time results in an error and the log of System also indicates some errors.

![errors](https://cloud.githubusercontent.com/assets/14545821/12949136/c1970994-d006-11e5-9fcf-654265169191.png)

````
root@rina-echo-time -c 10
24620(1453301930)#librina.logs (DBG): New log level: INFO
24620(1453301930)#librina.nl-manager (INFO): Netlink socket connected to local port 24620 
24620(1453301930)#rina-echo-time (ERR): Failed to allocate a flow
24620(1453301930)#rina-echo-time (ERR): Problems creating flow, exiting
SDUs sent: 0; SDUs received: 0; 0% SDU loss
Minimum RTT: 9.2234e+18 ms; Maximum RTT: 0 ms; Average RTT:0 ms; Standard deviation: -0 ms
````
Next hops Before failure
````
Name: /resalloc/nhopt/key=17-0; Class: NextHopTableEntry; Instance: 100
Value: Destination address: 17; QoS-id: 0; Cost: 1; Next hop addresses: 17/ 

Name: /resalloc/nhopt/key=18-0; Class: NextHopTableEntry; Instance: 101
Value: Destination address: 18; QoS-id: 0; Cost: 1; Next hop addresses: 18/ 

Name: /resalloc/nhopt/key=19-0; Class: NextHopTableEntry; Instance: 102
Value: Destination address: 19; QoS-id: 0; Cost: 1; Next hop addresses: 17/ 
````

Next hops After failure
````
Name: /resalloc/nhopt/key=18-0; Class: NextHopTableEntry; Instance: 155
Value: Destination address: 18; QoS-id: 0; Cost: 1; Next hop addresses: 18/ 

Name: /resalloc/nhopt/key=19-0; Class: NextHopTableEntry; Instance: 156
Value: Destination address: 19; QoS-id: 0; Cost: 1; Next hop addresses: 18
```

**Extra information**

- Debug options are disabled
- The latest commit of the used Pristine branch have the ids 9ce9644 and 1b4927e.
- I have also tried out the scenario that was executed in this [document](http://ict-pristine.eu/wp-content/uploads/2013/12/pristine_d62-use-case-trials-and-business-impact_draft.pdf) with the same configurations. The traffic did not reroute in my experiments and modifying the timers (e.g DeclaredDeadIntervalinMS) did not have an impact on the link failure resiliency.
- Afterwards I have used the multipath plugin developed by Javier Garcia which sent the PDUs through multiple paths. However, when I disconnected the same link as before (System 1 - System 2) the very same issue occurred

**Comment by edugrasa** [comment]
It should definitely work (we've tested it in other scenarios), so you've probably hit a but in our link-state routing policy implementation. Could you query the rib of the IPCP 1 (address 16) at system 1 before and after disconnecting the link? You have provided information on the next hops, but we would like to see the flow state objects also. And if you can do the same for IPCP 2 at system 2 (address 17) it would be great!

**Comment by jvleur** [comment]
Here you go.

[rib-system1-linkfail.txt](https://github.com/IRATI/stack/files/124955/rib-system1-linkfail.txt)
[rib-system1-pre-linkfail.txt](https://github.com/IRATI/stack/files/124954/rib-system1-pre-linkfail.txt)
[rib-system2-linkfail.txt](https://github.com/IRATI/stack/files/124953/rib-system2-linkfail.txt)
[rib-system2-pre-linkfail.txt](https://github.com/IRATI/stack/files/124952/rib-system2-pre-linkfail.txt)

**Comment by edugrasa** [comment]
The IPCP in system 1 still did not detect that the N-1 flow is "gone", so the N-1 flow is still there (and therefore there are no changes in routing); rib-system1-linkfail.txt shows that:

Name: /rmt/n1flows; Class: RMTN1Flows; Instance: 14
Value: -

Name: /rmt/n1flows/port_id=1; Class: RMTN1Flow; Instance: 34
Value: Port-id: 1; Enabled: 1; Queued pdus: 0; Dropped pdus: 0; Error pdus: 0
Tx: 12240 (bytes),  229 (pdus); Rx: 12500 (bytes), 231 (pdus)

Name: /rmt/n1flows/port_id=2; Class: RMTN1Flow; Instance: 41
Value: Port-id: 2; Enabled: 1; Queued pdus: 0; Dropped pdus: 0; Error pdus: 0
Tx: 3088 (bytes),  25 (pdus); Rx: 3287 (bytes), 27 (pdus)

The IPCP detects when an N-1 link is gone via the watchdog timers. By default they are configured with a very long period (I see that you are using the default configuration):

     "enrollmentTaskConfiguration" : {
        "policySet" : {
           "name" : "default",
           "version" : "1",
           "parameters" : [{
               "name"  : "enrollTimeoutInMs",
               "value" : "10000"
             },{
               "name"  : "watchdogPeriodInMs",
               "value" : "30000"
             },{
               "name"  : "declaredDeadIntervalInMs",
               "value" : "120000"
             },{
               "name"  : "neighborsEnrollerPeriodInMs",
               "value" : "30000"
             },{
               "name"  : "maxEnrollmentRetries",
               "value" : "3"
             }]
        }
     },

With this config you'd need to wait two minutes before the flow is declared dead. You can either wait this two minutes so that the N-1 flow is considered dead and routing is recomputed, or set lower values for these counters (such as 300 ms for the watchdog period and 1200 seconds for the declatedDeadInterval).

**Comment by dstaesse** [comment]
The system also listens to "ifconfig down" events (disabling the VLAN interface (ifconfig ethx.xxx down) is faster than disabling the physical interface (ifconfig ethx down). This is what we used in LFA. Blocking the VLAN in an intermediate switch or firewall will indeed need to wait for the watchdog.

**Comment by edugrasa** [comment]
Ok, I see you've added the RIB contents after the IPCP detects that the N-1 flow is gone, thanks! There are flow state objects that are missing, so definitely there is a bug in the propagation of those. We'll take a look at it!

**Comment by jvleur** [comment]
@edugrasa The declared-dead logs that I have uploaded were after the 2 minutes. After that any re-routing still did not occur.
@dstaesse I have done both disabling the interface and disabling the VLAN.

**Comment by dstaesse** [comment]
Ah, I misunderstood what you meant with "block the VLAN" then :)

**Comment by bernatgaston** [comment]
Hi, I think I have the fix to this bug. Could you test branch https://github.com/bernatgaston/stack/tree/pristine-1.4-neighbor_lost_routing please?

Please pull and install from this branch and test again. Even if it works, please paste me the RIB objects (FSOs and next hops) after the detection of the lost neighbor, to see if everyting is correct.

thanks

**Comment by jvleur** [comment]
We have tested the test branch and have come across several new issues that stopped us from testing whether our issue still remains. [Here](https://github.com/IRATI/stack/files/129878/bug-error.txt)
 is a file with more information but I summed up the issues.

The first failure is "modprobe: FATAL: Module default not found."  and we used a workaround to rename the rina-default-plugin.ko to default.ko. 

````
# cd /lib/modules/4.1.16/kernel/net/rina
# cp rina-default-plugin.ko default.ko
# depmod -a
````
However, this prevented us from enrolling.
````
ipcp: /root/stack/bug/stack/rinad/src/ipcp/enrollment-task.cc:698: virtual void rinad::EnrollmentTask::processEnrollmentRequestEvent(rina::EnrollToDAFRequestEvent*): Assertion `nsmps' failed.
````
When the IPCM got terminated it ended with the error:
````
rina-kipcm(ERR): Could not find IPC process with id 3
````

**Comment by edugrasa** [comment]
rina-default-plugin.ko must not be renamed, this is the correct name of the kernel module. 

I think the problem may either be the configuration file or maybe some compilation error that was not notified. Could you post the configuration? Thanks!

**Comment by edugrasa** [comment]
BTW, when testing Bernat's branch, did you rebuild and reinstall user-space parts?

**Comment by jvleur** [comment]
The configuration files are the same as I posted in the initial issue post. The install-user-from-scratch script is used to reinstall the user space. Also rebuilding the kernel did not solve the issue.

**Comment by edugrasa** [comment]
Does the IPCM continue after the "modprobe: FATAL: Module default not found." error, or does it halt? (If it continues you can ignore it). Could you check that there are a bunch of files starting by "default" in the /usr/local/irati/lib/rinad/ipcp folder?

Please do not rename the rina-default-plugin.ko to default.ko. The plugin called "default" is a user-space plugin (for the IPCP Daemon), not a kernel plugin. When you've renamed it, the user-space plugin has not been loaded, and as a result the "assign to dif" command has failed (which can be seen in the status of IPCP 3 - INITIALIZED- instead of -ASSIGNED TO DIF-).

```
# list-ipcps 
IPCM >>> Current IPC processes (id | name | type | state | Registered applications | Port-ids of flows provided)
    1 | test-eth-vlan:1:: | shim-eth-vlan | ASSIGNED TO DIF 101 | IPCP1.IRATI-1-- | -
    2 | test-eth-vlan2:1:: | shim-eth-vlan | ASSIGNED TO DIF 102 | IPCP1.IRATI-1-- | -
    3 | IPCP1.IRATI:1:: | normal-ipc | INITIALIZED | - | -

**Comment by JcKlomp** [comment]
Hi, I am working on this with @jvleur.

I can confirm that there are several files in /usr/local/irati/lib/rinad/ipcp that start with "default".
The reason why we copied rina-default-plugin.ko to default.ko is that a strace shows the ipcm is modprobing for "default" instead of "rina-default-plugin" (as it did previously), and yes this error is fatal-ish.

```
[pid  4503] execve("/sbin/modprobe", ["modprobe", "default"], [/* 14 vars */]) = 0
[pid  4503] arch_prctl(ARCH_SET_FS, 0x7fa1d8742700) = 0
modprobe: FATAL: Module default not found.
[pid  4503] exit_group(1)               = ?
[pid  4503] +++ exited with 1 +++
```
```
# list-ipcps 
IPCM >>> Current IPC processes (id | name | type | state | Registered applications | Port-ids of flows provided)
    1 | IPCP1.IRATI:1:: | normal-ipc | ASSIGNED TO DIF normal.DIF | - | -
```

**Comment by edugrasa** [comment]
@vmaffione could you take a look? (since it seems plugin loading related ...)

**Comment by vmaffione** [comment]
Hi, please do not rename rina-default-plugin.ko into default.ko, it won't work.

There are two "default" plugins, and IRATI needs both:
  - default.so, which is the default plugin for userspace, and is installed where the userspace part of IRATI is installed
  - rina-default-plugin.ko, which is the default plugin for kernelspace and is installed into /lib/modules/4.1.16-irati/kernel/net/rina

The current IPCM implementation does not know when a plugin is for userspace or kernelspace. The strategy is therefore the following: Given a plugin name, the IPCM first tries to see if it is a kernelspace plugin,  and so tries to modprobe it. If it fails (because the plugin is for userspace, or because no such plugin exists), it tries to dlopen() it.

So, in every case, the IPCM will try to modprobe "rina-default-plugin" --> this MUST succeed (since rina-default-plugin is an kernelspace plugin), otherwise your installation is broken.
Then it will try to modprobe "default", which will fail because "default" is an userspace plugin. Ignore this error message, which is not fatal. Right afterwards, the IPCM will try to dlopen() "default" --> it MUST succeed, otherwise your installation is broken.

**Comment by jvleur** [comment]
My apologies for the lack of updates. We are currently unable to provide more feedback on this issue. The provided details on our installation in this issue have not changed since our last comment.

**Comment by vmaffione** [comment]
Could you try to remove the existing installation, then install the kernel
again, and run the install-user-from-scratch, without moving or renaming
any files, and use a correct  "pluginsPath" in the IPCM configuration files
(as shown by the examples in tests/conf) ?

2016-02-26 23:43 GMT+01:00 jvleur <notifications@github.com>:

> My apologies for the lack of updates. We are currently unable to provide
> more feedback on this issue. The provided details on our installation in
> this issue have not changed since our last comment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IRATI/stack/issues/864#issuecomment-189514033>.
>



-- 
Vincenzo Maffione

**Comment by edugrasa** [comment]
Fixed by #876, merged in pristine-1.4. Could you try with pristine-1.4 again?

**Comment by JcKlomp** [comment]
We've tried it out (no problems this time with launching) but the issue is unfortunately not resolved in https://github.com/IRATI/stack/commit/451bd790ec22173682f5ef58fc4b8c2d959344ec.
System 4 keeps trying to send traffic to System 1 via System 2 over vlan 103 (after eth1, vlan 101 of System 1 is shut down and the timers have expired) but System 2 can't deliver it (or establish the flow for that matter).
Like we said we are currently quite busy, but will try to provide more details if time allows.

**Comment by edugrasa** [comment]
Ok, please do if you can :)
I've tried the fix in a simple setup (ring of 3 nodes), I'll try in a more complex scenario.

**Comment by edugrasa** [comment]
I've re-created your scenario and tried with latest pristine-1.4, the bug seems indeed to be fixed. Next-hop table of ipcp1 before bringing down the eth interface between ipcp1 and ipcp2:

Name: /resalloc/nhopt/key=16-0; Class: NextHopTableEntry; Instance: 53
Value: Destination address: 16; QoS-id: 0; Cost: 1; Next hop addresses: 17/ 

Name: /resalloc/nhopt/key=17-0; Class: NextHopTableEntry; Instance: 54
Value: Destination address: 17; QoS-id: 0; Cost: 1; Next hop addresses: 17/ 

Name: /resalloc/nhopt/key=18-0; Class: NextHopTableEntry; Instance: 55
Value: Destination address: 18; QoS-id: 0; Cost: 1; Next hop addresses: 18/

After:

Name: /resalloc/nhopt/key=17-0; Class: NextHopTableEntry; Instance: 71
Value: Destination address: 17; QoS-id: 0; Cost: 1; Next hop addresses: 18/ 

Name: /resalloc/nhopt/key=18-0; Class: NextHopTableEntry; Instance: 72
Value: Destination address: 18; QoS-id: 0; Cost: 1; Next hop addresses: 18/ 

Name: /resalloc/nhopt/key=19-0; Class: NextHopTableEntry; Instance: 73
Value: Destination address: 19; QoS-id: 0; Cost: 1; Next hop addresses: 18/

**Comment by JcKlomp** [comment]
That looks promising. Unfortunately, we're currently running into several deadlines so can't verify it at the moment.
We expect that we can do this at the end of next week.

**Comment by vmaffione** [comment]
@jvleur do you have any update on this?

**Comment by jvleur** [comment]
My apologies for this late response, we are unable to verify the bug due to the lack of time. Therefore I would like to ask if its possible to close this issue based on the results of @edugrasa .
